- name: visualstudio-project playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
  - namespace: dotnet-dev
  - git_repo: https://github.com/redhat-developer/s2i-dotnetcore-ex.git
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: provision-visualstudio-project
    playbook_debug: true
