---
#############################################################################
# Provision visualstudio-build
#############################################################################
- include: visualstudio.yml
- include: openshift.yml
- include: start.yml

#############################################################################
# Bindable services must make credentials available to the Ansible Service
# Broker during the provision stage.  They will later be made available to
# applications after a binding is created.
# https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/design.md#using-a-service-instance
#############################################################################
- name: encode bind credentials
  asb_encode_binding:
    fields:
      username: "{{ vsts_username }}"
      password: "{{ vsts_password }}"
      project_url: "{{ vstsProject.json.url }}"
      project_id: "{{ vstsProject.json.id }}"
      git_url: "{{ vstsGitRepo.json.remoteUrl }}"
  tags:
  - always
