apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: {{ project_name }}
  name: {{ project_name }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ project_name }}:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://{{ vsts_instance }}.visualstudio.com/_git/{{ project_name }}
      sourceSecret:
        name: git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:6
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: 8kdCwBdWpup5OydYqXCj
    type: GitHub
  - generic:
      secret: wuve0D41bIFHPU_DzT5-
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
