apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  annotations:
    build.openshift.io/source-secret-match-uri-1: {{ vstsGitRepo.json.remoteUrl }}/*
  creationTimestamp: null
  name: git
data:
  username: {{ vsts_username | b64encode }}
  password: {{ vsts_password | b64encode }}
