apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ project_name }}
  name: {{ project_name }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ project_name }}
    deploymentconfig: {{ project_name }}
