---
#############################################################################
# Provision openshift-build
#############################################################################
- name: "Delete OpenShift Git Secret"
  k8s_v1_secret:
    namespace: "{{ namespace }}"
    verify_ssl: false
    name: git
    state: absent
  tags:
  - openshift

- name: "Delete OpenShift ImageStream"
  openshift_v1_image_stream:
    namespace: "{{ namespace }}"
    verify_ssl: false
    name: "{{ namespace }}"
    state: absent
  tags:
  - openshift

- name: "Delete OpenShift BuildConfig"
  openshift_v1_build_config:
    namespace: "{{ namespace }}"
    verify_ssl: false
    name: "{{ namespace }}"
    state: absent
  tags:
  - openshift

- name: "Delete OpenShift DeploymentConfig"
  openshift_v1_deployment_config:
    namespace: "{{ namespace }}"
    verify_ssl: false
    name: "{{ namespace }}"
    state: absent
  tags:
  - openshift

- name: "Delete OpenShift Service"
  k8s_v1_service:
    namespace: "{{ namespace }}"
    verify_ssl: false
    name: "{{ namespace }}"
    state: absent
  tags:
  - openshift
